Days component
asiimwe-a/mentorship-weather-app pull request #8
Opened 2023-03-10 21:23 UTC by gitahievans

## Description
In this pull request, I have created a component called Days, that houses cards showing weather data for each day. 

![Screenshot from 2023-03-11 00-14-32](https://user-images.githubusercontent.com/106302681/224430437-3e025ed5-07e3-41aa-9093-6e005d9092fb.png)

2023-03-11 00:14 UTC, daveclinton requested changes

2023-03-11 00:14 UTC, daveclinton commented on src/components/GetApi/index.tsx
> +export default Index;
This change appears to be a duplicate of this Pull Request https://github.com/asiimwe-a/mentorship-weather-app/pull/9

2023-03-11 00:14 UTC, daveclinton commented on src/components/Days/index.tsx
> +                direction="column"
use flexDir instead of direction

2023-03-12 03:27 UTC, gitahievans commented on src/components/Days/index.tsx
> +                direction="column"
Done

2023-03-13 18:09 UTC, closed without merging